import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import{BsFillCpuFill} from 'react-icons/bs'
import { CgDarkMode } from "react-icons/cg";
import{AiFillBehanceSquare, AiFillLinkedin, AiFillInstagram, } from "react-icons/ai";
import Image from 'next/image';
import deved from '../public/avatarilham2.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web7.png'
import web2 from '../public/web8.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import {useState} from "react"
export default function Home() {
  const [darkMode, setDarkMode] =useState(false);
  return (
    <div className={darkMode ? "dark":""} >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-slate-50 px-10 md:px-20 lg:px-40 dark:bg-gray-900' >
         <section className="min-h-screen">
            <nav className='p-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>Portofolio ilham</h1>
              <ul className='flex items-center'>
                <li><CgDarkMode onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer text-gray-800 text-3xl
                dark:text-white' /></li>
                <li><a
                 className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'  download="cv.pdf" href='/file/cv.pdf'>Resume</a></li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>lham Saputro</h2>
              <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer and Designer</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad illo quae natus dignissimos officiis nam dolore nesciunt odit distinctio beatae, asperiores alias mollitia! Distinctio corrupti ipsa quasi. Placeat, explicabo obcaecati.</p>
            </div>
            <div className='text-5xl flex justify-center gap-6 py-3 text-blue-900 dark:text-blue-100'>
              <Link href="https://www.behance.net/ilhamsaputro">
              <AiFillBehanceSquare  />
              </Link>
              <Link href="https://www.linkedin.com/in/ilham-saputro-16919b194">
              
              <AiFillLinkedin/>
              </Link>
              <Link href="https://www.instagram.com/ilhamsaputro12/">
              
              <AiFillInstagram/>
              </Link>
            </div>
            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} layout="fill"  objectFit='cover'/>
            </div>
         </section>
         {/* end of section 1 */}
         <section>
           <div className='text-center py-3 dark:text-white'>
            <h3 className='text-3xl py-1'>
              Service I offer
            </h3>
            <p className='text-md leading-8 text-gray-80 md:text-xl max-w-xl mx-auto'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad illo quae natus dignissimos officiis nam dolore nesciunt odit distinctio beatae, asperiores alias mollitia! Distinctio corrupti ipsa quasi. Placeat, explicabo obcaecati</p>
            <p className='text-md leading-8 text-gray-80 md:text-xl max-w-xl mx-auto'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad illo quae natus dignissimos officiis nam dolore nesciunt odit distinctio beatae, asperiores alias mollitia! Distinctio corrupti ipsa quasi. Placeat, explicabo obcaecati</p>
           </div> 
           <div className='lg:flex gap-10'>
           {/* gambar 1 atau card 1 */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <div  >
              <Image className='relative mx-auto' src={design} width={100} height={100} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
              <p className='py-2'>
                Creating elegant designs suited for your design theory
              </p>
              <h4 className='py-4 text-teal-600'>Design tool i use</h4>
              <p className='text-gray-800 py-1'>Photosop</p>
              <p className='text-gray-800 py-1'>Adobe Ilustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            {/* gambar 2 atau card 2 */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white '>
              <div >

              <Image className='relative mx-auto' src={code} width={100} height={100} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
              <p className='py-2'>
                Creating elegant designs suited for your design theory
              </p>
              <h4 className='py-4 text-teal-600'>Design tool i use</h4>
              <p className='text-gray-800 py-1'>Photosop</p>
              <p className='text-gray-800 py-1'>Adobe Ilustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            {/* gambar 3 atau card 3 */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white '>
              <div >

              <Image className='relative mx-auto' src={consulting} width={100} height={100} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
              <p className='py-2'>
                Creating elegant designs suited for your design theory
              </p>
              <h4 className='py-4 text-teal-600'>Design tool i use</h4>
              <p className='text-gray-800 py-1'>Photosop</p>
              <p className='text-gray-800 py-1'>Adobe Ilustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
           </div>
         </section>
         <section>
          <div className=' dark:text-white'>

          <h3 className='text-3xl py-1'>
            Portofolio
          </h3> 
          <p className='text-md leading-8 text-gray-80'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad illo quae natus dignissimos officiis nam dolore nesciunt odit distinctio beatae, asperiores alias mollitia! Distinctio corrupti ipsa quasi. Placeat, explicabo obcaecati</p>
            <p className='text-md leading-8 text-gray-80'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad illo quae natus dignissimos officiis nam dolore nesciunt odit distinctio beatae, asperiores alias mollitia! Distinctio corrupti ipsa quasi. Placeat, explicabo obcaecati</p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'> 
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
          </div>
         </section>
      </main>

     
    </div>
  )
}
